import type { WithIntelligence } from "../types";
import type {
  YOUTUBE_SEARCH_CHANNEL_ITEM,
  YOUTUBE_SEARCH_RESPONSE,
  YOUTUBE_SEARCH_VIDEO_ITEM,
} from "../../search/types";
import type {
  YOUTUBE_INTELLIGENCE_CHANNEL_TIER_DISTRIBUTION,
  YOUTUBE_INTELLIGENCE_CHANNEL_TIER_FIELD,
  YOUTUBE_INTELLIGENCE_DURATION_BUCKET_DISTRIBUTION,
  YOUTUBE_INTELLIGENCE_DURATION_FIELDS,
  YOUTUBE_INTELLIGENCE_PERCENTILE_DISTRIBUTION,
  YOUTUBE_INTELLIGENCE_PUBLISHING_FIELDS,
  YOUTUBE_INTELLIGENCE_TITLE_TEXT_FIELDS,
} from "../types";

export type YOUTUBE_SEARCH_VIDEO_ITEM_ENRICHED = YOUTUBE_SEARCH_VIDEO_ITEM & {
  publishedAt: string | null;
  channelSubscribers: number | null;
};

export type YOUTUBE_SEARCH_VIDEO_INTELLIGENCE_FIELDS =
  YOUTUBE_INTELLIGENCE_PUBLISHING_FIELDS &
    Pick<YOUTUBE_INTELLIGENCE_CHANNEL_TIER_FIELD, "channelTier"> & {
      velocityScore: number | null;
    } & YOUTUBE_INTELLIGENCE_DURATION_FIELDS &
    YOUTUBE_INTELLIGENCE_TITLE_TEXT_FIELDS & {
      descriptionLength: number | null;
    };

export type YOUTUBE_SEARCH_CHANNEL_INTELLIGENCE_FIELDS =
  YOUTUBE_INTELLIGENCE_CHANNEL_TIER_FIELD;

export type YOUTUBE_SEARCH_VIDEO_ITEM_INTELLIGENCE = WithIntelligence<
  YOUTUBE_SEARCH_VIDEO_ITEM_ENRICHED,
  YOUTUBE_SEARCH_VIDEO_INTELLIGENCE_FIELDS
>;

export type YOUTUBE_SEARCH_CHANNEL_ITEM_INTELLIGENCE = WithIntelligence<
  YOUTUBE_SEARCH_CHANNEL_ITEM,
  YOUTUBE_SEARCH_CHANNEL_INTELLIGENCE_FIELDS
>;

export type YOUTUBE_SEARCH_ITEM_INTELLIGENCE =
  | YOUTUBE_SEARCH_VIDEO_ITEM_INTELLIGENCE
  | YOUTUBE_SEARCH_CHANNEL_ITEM_INTELLIGENCE;

export type YOUTUBE_SEARCH_INTELLIGENCE_FIELDS = {
  avgViewsPerDay: number | null;
  avgTitleLength: number | null;
  shortRatio: number | null;
  titleWithNumberRatio: number;
  titleWithQuestionRatio: number;
  durationBucketDistribution: YOUTUBE_INTELLIGENCE_DURATION_BUCKET_DISTRIBUTION;
  channelTierDistribution: YOUTUBE_INTELLIGENCE_CHANNEL_TIER_DISTRIBUTION;
  estimatedSaturation: number | null;
  avgVelocityScore: number | null;
  topVelocityScore: number | null;
  velocityDistribution: YOUTUBE_INTELLIGENCE_PERCENTILE_DISTRIBUTION;
};

export type YOUTUBE_SEARCH_INTELLIGENCE_RESPONSE = Omit<
  YOUTUBE_SEARCH_RESPONSE,
  "items"
> & {
  items: YOUTUBE_SEARCH_ITEM_INTELLIGENCE[];
  intelligence: YOUTUBE_SEARCH_INTELLIGENCE_FIELDS;
};
