// Smoke test: exercise the `fetchYoutubeVideoTranscript` API helper end-to-end
// across diverse video types (manual captions, ASR-only, music, tech talk).
//
// Run: pnpm exec tsx scripts/youtube-transcript-api-smoke.ts
//
// Each fixture is a representative video ID; the test asserts that:
//   - the response has at least one line
//   - `fullText` is non-empty
//   - `availableTracks` is non-empty
//   - the selected language appears in `availableTracks`
//
// Network-dependent: requires Evomi proxy or direct YouTube access.
import "dotenv/config";
import { fetchYoutubeVideoTranscript } from "../src/api/youtube/transcript";

type Fixture = {
  videoId: string;
  language: string;
  description: string;
  /** Minimum expected line count (loose lower bound to keep the test stable). */
  minLines?: number;
};

const FIXTURES: Fixture[] = [
  {
    videoId: "aircAruvnKk",
    language: "en",
    description: "Tech talk (3Blue1Brown — neural networks) with manual EN captions",
    minLines: 50,
  },
  {
    videoId: "dQw4w9WgXcQ",
    language: "en",
    description: "Music video (Rick Astley) with manual EN captions",
    minLines: 10,
  },
  {
    videoId: "9bZkp7q19f0",
    language: "en",
    description: "PSY — Gangnam Style (likely ASR-only EN)",
    minLines: 10,
  },
  {
    videoId: "kJQP7kiw5Fk",
    language: "es",
    description: "Luis Fonsi — Despacito (request Spanish track)",
    minLines: 5,
  },
];

type Result = {
  fixture: Fixture;
  ok: boolean;
  lines: number;
  fullTextLength: number;
  language: string;
  isAutoGenerated: boolean;
  trackCount: number;
  firstLine?: string;
  failures: string[];
  error?: string;
};

async function runFixture(fixture: Fixture): Promise<Result> {
  const failures: string[] = [];
  try {
    const result = await fetchYoutubeVideoTranscript({
      country: "US",
      region: undefined,
      videoId: fixture.videoId,
      language: fixture.language,
    });

    if (result.lines.length === 0) failures.push("expected at least one line");
    if (result.fullText.trim().length === 0) failures.push("expected non-empty fullText");
    if (result.availableTracks.length === 0) failures.push("expected at least one available track");
    if (!result.availableTracks.some((t) => t.languageCode === result.language)) {
      failures.push(
        `expected selected language "${result.language}" in availableTracks`,
      );
    }
    if (fixture.minLines && result.lines.length < fixture.minLines) {
      failures.push(
        `expected at least ${fixture.minLines} lines, got ${result.lines.length}`,
      );
    }

    return {
      fixture,
      ok: failures.length === 0,
      lines: result.lines.length,
      fullTextLength: result.fullText.length,
      language: result.language,
      isAutoGenerated: result.isAutoGenerated,
      trackCount: result.availableTracks.length,
      firstLine: result.lines[0]?.text.slice(0, 80),
      failures,
    };
  } catch (err) {
    return {
      fixture,
      ok: false,
      lines: 0,
      fullTextLength: 0,
      language: fixture.language,
      isAutoGenerated: false,
      trackCount: 0,
      failures: ["threw: " + (err instanceof Error ? err.message : String(err))],
      error: err instanceof Error ? err.message : String(err),
    };
  }
}

async function main() {
  console.log(`[smoke] running ${FIXTURES.length} fixtures\n`);

  const results: Result[] = [];
  for (const fixture of FIXTURES) {
    process.stdout.write(`[smoke] ${fixture.videoId} (${fixture.language}) — ${fixture.description} ... `);
    const result = await runFixture(fixture);
    console.log(result.ok ? "PASS" : "FAIL");
    results.push(result);
  }

  console.log("\n[smoke] summary:");
  for (const r of results) {
    const status = r.ok ? "PASS" : "FAIL";
    console.log(
      `  ${status}  ${r.fixture.videoId}  lines=${r.lines}  tracks=${r.trackCount}  lang=${r.language}${r.isAutoGenerated ? "*" : ""}  fullText=${r.fullTextLength}`,
    );
    if (r.firstLine) {
      console.log(`        first: ${r.firstLine}`);
    }
    if (r.failures.length) {
      for (const f of r.failures) console.log(`        ✗ ${f}`);
    }
  }

  const failed = results.filter((r) => !r.ok);
  if (failed.length > 0) {
    console.error(`\n[smoke] ${failed.length}/${results.length} fixtures FAILED`);
    process.exit(1);
  }
  console.log(`\n[smoke] all ${results.length} fixtures PASS`);
}

main().catch((err) => {
  console.error("[smoke] FAILED:", err);
  process.exit(1);
});
