import {
  YOUTUBE_TIMEDTEXT_FMT_PARAM_PATTERN,
  YOUTUBE_TRANSCRIPT_TRACK_KIND,
} from "./constants";
import type {
  INNERTUBE_CAPTION_TRACK,
  JSON3_RESPONSE,
  YOUTUBE_TRANSCRIPT_LINE,
  YOUTUBE_TRANSCRIPT_TRACK,
} from "./types";

/** Joins a caption track's `name.runs` or returns `simpleText`, else null. */
export function trackName(track: INNERTUBE_CAPTION_TRACK): string | null {
  const simple = track.name?.simpleText;
  if (simple) return simple;
  const runs = track.name?.runs;
  if (runs?.length) return runs.map((r) => r.text).join("");
  return null;
}

/** Converts a raw InnerTube caption track to the public track-info shape. */
export function toTrackInfo(
  track: INNERTUBE_CAPTION_TRACK,
): YOUTUBE_TRANSCRIPT_TRACK {
  const kind = track.kind ?? null;
  return {
    languageCode: track.languageCode,
    kind,
    name: trackName(track),
    isAutoGenerated: kind === YOUTUBE_TRANSCRIPT_TRACK_KIND.ASR,
  };
}

/**
 * Picks the best caption track for the requested language.
 *
 * Preference order:
 *   1. Exact language code, non-ASR (manually authored).
 *   2. Exact language code, any kind.
 *   3. Language prefix match (e.g. "en-US" for requested "en"), non-ASR.
 *   4. Language prefix match, any kind.
 *   5. First available track.
 */
export function pickTrack(
  tracks: INNERTUBE_CAPTION_TRACK[],
  language: string,
): INNERTUBE_CAPTION_TRACK | null {
  if (tracks.length === 0) return null;
  const lang = language.toLowerCase();

  const exactNonAsr = tracks.find(
    (t) =>
      t.languageCode.toLowerCase() === lang &&
      t.kind !== YOUTUBE_TRANSCRIPT_TRACK_KIND.ASR,
  );
  if (exactNonAsr) return exactNonAsr;

  const exactAny = tracks.find(
    (t) => t.languageCode.toLowerCase() === lang,
  );
  if (exactAny) return exactAny;

  const prefixNonAsr = tracks.find(
    (t) =>
      t.languageCode.toLowerCase().startsWith(`${lang}-`) &&
      t.kind !== YOUTUBE_TRANSCRIPT_TRACK_KIND.ASR,
  );
  if (prefixNonAsr) return prefixNonAsr;

  const prefixAny = tracks.find((t) =>
    t.languageCode.toLowerCase().startsWith(`${lang}-`),
  );
  if (prefixAny) return prefixAny;

  return tracks[0] ?? null;
}

/** Strips any existing `fmt=` query param from a timedtext `baseUrl`. */
export function stripFmtParam(baseUrl: string): string {
  return baseUrl.replace(YOUTUBE_TIMEDTEXT_FMT_PARAM_PATTERN, "");
}

/** Flattens a JSON3 timedtext response into ordered transcript lines. */
export function parseJson3Events(
  json3: JSON3_RESPONSE,
): YOUTUBE_TRANSCRIPT_LINE[] {
  const events = json3.events ?? [];
  const lines: YOUTUBE_TRANSCRIPT_LINE[] = [];

  for (const ev of events) {
    const text = (ev.segs ?? [])
      .map((s) => s.utf8 ?? "")
      .join("")
      .replace(/\n/g, " ")
      .trim();
    if (!text) continue;
    lines.push({
      startMs: ev.tStartMs ?? 0,
      durationMs: ev.dDurationMs ?? null,
      text,
    });
  }

  return lines;
}

/** Joins transcript lines into a single space-separated string. */
export function joinTranscriptLines(lines: YOUTUBE_TRANSCRIPT_LINE[]): string {
  return lines.map((l) => l.text).join(" ");
}
