import {
  createYoutubeFetchSession,
  resolveYoutubeGeo,
} from "../helpers";
import {
  closeUrlFetchSession,
  type UrlFetchSession,
} from "../../../utils/node-tls-client-session-handler";
import { YOUTUBE_TRANSCRIPT_TRACK_KIND } from "./constants";
import { fetchPlayerCaptionTracks, fetchTimedTextJson3 } from "./fetch";
import { joinTranscriptLines, pickTrack, toTrackInfo } from "./compute";
import type {
  YOUTUBE_VIDEO_TRANSCRIPT_REQUEST,
  YOUTUBE_VIDEO_TRANSCRIPT_RESPONSE,
} from "./types";

export {
  fetchPlayerCaptionTracks,
  fetchTimedTextJson3,
} from "./fetch";
export {
  joinTranscriptLines,
  parseJson3Events,
  pickTrack,
  stripFmtParam,
  toTrackInfo,
  trackName,
} from "./compute";

/**
 * Fetches the English (or requested language) transcript for a YouTube video.
 *
 * Strategy (as of 2026, bypassing PO Token / BotGuard attestation):
 *   1. POST `/youtubei/v1/player` with the iOS InnerTube client to get
 *      `captionTracks[]` with per-language `baseUrl`s.
 *   2. GET `baseUrl + &fmt=json3` to fetch the timedtext JSON3 payload.
 *   3. Flatten `events[].segs[].utf8` into ordered transcript lines.
 *
 * The iOS client is exempt from the attestation requirement that blocks
 * WEB and ANDROID clients from server-side transcript access.
 */
export async function fetchYoutubeVideoTranscript(
  request: YOUTUBE_VIDEO_TRANSCRIPT_REQUEST,
): Promise<YOUTUBE_VIDEO_TRANSCRIPT_RESPONSE> {
  const { videoId, language, country, region } = request;
  const { gl } = resolveYoutubeGeo({ country, region });

  const session: UrlFetchSession = await createYoutubeFetchSession({
    country,
    region,
  });

  try {
    const tracks = await fetchPlayerCaptionTracks(session, videoId, gl);
    const availableTracks = tracks.map(toTrackInfo);

    const selected = pickTrack(tracks, language);
    if (!selected) {
      throw new Error(
        `No caption track available for language "${language}". Available: ${
          availableTracks.map((t) => t.languageCode).join(", ") || "none"
        }`,
      );
    }

    const lines = await fetchTimedTextJson3(session, selected, videoId);
    const fullText = joinTranscriptLines(lines);

    return {
      videoId,
      language: selected.languageCode,
      isAutoGenerated: selected.kind === YOUTUBE_TRANSCRIPT_TRACK_KIND.ASR,
      availableTracks,
      lines,
      fullText,
    };
  } finally {
    await closeUrlFetchSession(session);
  }
}
