import type { z } from "zod";
import type { YOUTUBE_VIDEO_TRANSCRIPT_REQUEST_SCHEMA } from "./schemas";

export type YOUTUBE_VIDEO_TRANSCRIPT_REQUEST = z.infer<
  typeof YOUTUBE_VIDEO_TRANSCRIPT_REQUEST_SCHEMA
>;

export type YOUTUBE_TRANSCRIPT_LINE = {
  /** Start time of the line, in milliseconds. */
  startMs: number;
  /** Duration of the line, in milliseconds (when available). */
  durationMs: number | null;
  /** Plain-text content of the line. */
  text: string;
};

export type YOUTUBE_TRANSCRIPT_TRACK = {
  languageCode: string;
  /** Track kind, e.g. "asr" for auto-generated captions. */
  kind: string | null;
  /** Human-readable language name (e.g. "English"). */
  name: string | null;
  /** Whether this track was auto-generated. */
  isAutoGenerated: boolean;
};

export type YOUTUBE_VIDEO_TRANSCRIPT_RESPONSE = {
  videoId: string;
  /** BCP-47 language code of the selected track. */
  language: string;
  /** Whether the returned track is auto-generated (ASR). */
  isAutoGenerated: boolean;
  /** All caption tracks available for the video. */
  availableTracks: YOUTUBE_TRANSCRIPT_TRACK[];
  /** Transcript lines, ordered by time. */
  lines: YOUTUBE_TRANSCRIPT_LINE[];
  /** Full transcript joined into a single string. */
  fullText: string;
};

// ─── InnerTube raw response shapes (internal — not exported) ────────────────────

export type INNERTUBE_CAPTION_TRACK = {
  baseUrl: string;
  languageCode: string;
  kind?: string;
  name?: { simpleText?: string; runs?: Array<{ text: string }> };
  vssId?: string;
};

export type INNERTUBE_PLAYER_RESPONSE = {
  playabilityStatus?: { status?: string; reason?: string };
  captions?: {
    playerCaptionsTracklistRenderer?: {
      captionTracks?: INNERTUBE_CAPTION_TRACK[];
    };
  };
};

// ─── timedtext JSON3 raw response shape (internal — not exported) ──────────────

export type JSON3_EVENT = {
  tStartMs?: number;
  dDurationMs?: number;
  segs?: Array<{ utf8?: string }>;
};

export type JSON3_RESPONSE = {
  events?: JSON3_EVENT[];
};
