import type { WithIntelligence } from "../types";
import type {
  YOUTUBE_CHANNEL_RESPONSE,
  YOUTUBE_CHANNEL_VIDEO_ITEM,
  YOUTUBE_CHANNEL_SHORT_ITEM,
  YOUTUBE_CHANNEL_PLAYLIST_ITEM,
} from "../../channel/types";
import type {
  YOUTUBE_INTELLIGENCE_CHANNEL_TIER_FIELD,
  YOUTUBE_INTELLIGENCE_DESCRIPTION_LENGTH_FIELD,
  YOUTUBE_INTELLIGENCE_DURATION_FIELDS,
  YOUTUBE_INTELLIGENCE_PERCENTILE_DISTRIBUTION,
  YOUTUBE_INTELLIGENCE_PUBLISHING_FIELDS,
  YOUTUBE_INTELLIGENCE_TITLE_LENGTH_FIELD,
  YOUTUBE_INTELLIGENCE_TITLE_PATTERN_FIELDS,
  YOUTUBE_INTELLIGENCE_TITLE_TEXT_FIELDS,
  YOUTUBE_INTELLIGENCE_VELOCITY_SCORE_FIELD,
  YOUTUBE_RECENT_VELOCITY_TREND_VALUE,
} from "../types";

export type YOUTUBE_CHANNEL_VIDEO_ITEM_ENRICHED = YOUTUBE_CHANNEL_VIDEO_ITEM & {
  publishedAt: string | null;
  duration: number | null;
  likeCount: number | null;
  commentCount: number | null;
};

export type YOUTUBE_CHANNEL_VIDEO_INTELLIGENCE_FIELDS =
  YOUTUBE_INTELLIGENCE_TITLE_TEXT_FIELDS &
    YOUTUBE_INTELLIGENCE_PUBLISHING_FIELDS &
    YOUTUBE_INTELLIGENCE_DURATION_FIELDS &
    YOUTUBE_INTELLIGENCE_DESCRIPTION_LENGTH_FIELD &
    YOUTUBE_INTELLIGENCE_VELOCITY_SCORE_FIELD & {
      engagementRatio: number | null;
      rankOnChannel: number | null;
      viewsVsChannelAvg: number | null;
    };

export type YOUTUBE_CHANNEL_INTELLIGENCE_FIELDS = {
  channelAgeInDays: number | null;
  avgViewsPerVideo: number | null;
  uploadsPerWeek: number | null;
  subscriberEfficiencyRatio: number | null;
  viewsPerSubscriber: number | null;
  isKidsChannel: boolean | null;
  keywordCount: number;
  shortCount: number | null;
  videoOnlyCount: number | null;
  shortRatio: number | null;
  shortRatioCensored: boolean;
  avgVideoDuration: number | null;
  topVideoViewCount: number | null;
  bottomVideoViewCount: number | null;
  velocityDistribution: YOUTUBE_INTELLIGENCE_PERCENTILE_DISTRIBUTION;
  uploadsLast30Days: number | null;
  uploadsLast90Days: number | null;
  recentVelocityTrend: YOUTUBE_RECENT_VELOCITY_TREND_VALUE | null;
} & YOUTUBE_INTELLIGENCE_CHANNEL_TIER_FIELD;

export type YOUTUBE_CHANNEL_SHORT_ITEM_ENRICHED = YOUTUBE_CHANNEL_SHORT_ITEM & {
  publishedAt: string | null;
  duration: number | null;
};

export type YOUTUBE_CHANNEL_SHORT_INTELLIGENCE_FIELDS =
  YOUTUBE_INTELLIGENCE_PUBLISHING_FIELDS &
    YOUTUBE_INTELLIGENCE_DURATION_FIELDS &
    YOUTUBE_INTELLIGENCE_TITLE_TEXT_FIELDS &
    YOUTUBE_INTELLIGENCE_DESCRIPTION_LENGTH_FIELD & {
      rankOnChannel: number | null;
      viewsVsChannelAvg: number | null;
    };

export type YOUTUBE_CHANNEL_PLAYLIST_INTELLIGENCE_FIELDS = Record<
  string,
  never
>;

export type YOUTUBE_CHANNEL_VIDEO_ITEM_INTELLIGENCE = WithIntelligence<
  YOUTUBE_CHANNEL_VIDEO_ITEM_ENRICHED,
  YOUTUBE_CHANNEL_VIDEO_INTELLIGENCE_FIELDS
>;

export type YOUTUBE_CHANNEL_SHORT_ITEM_INTELLIGENCE = WithIntelligence<
  YOUTUBE_CHANNEL_SHORT_ITEM_ENRICHED,
  YOUTUBE_CHANNEL_SHORT_INTELLIGENCE_FIELDS
>;

export type YOUTUBE_CHANNEL_PLAYLIST_ITEM_INTELLIGENCE = WithIntelligence<
  YOUTUBE_CHANNEL_PLAYLIST_ITEM,
  YOUTUBE_CHANNEL_PLAYLIST_INTELLIGENCE_FIELDS
>;

export type YOUTUBE_CHANNEL_ITEM_INTELLIGENCE =
  | YOUTUBE_CHANNEL_VIDEO_ITEM_INTELLIGENCE
  | YOUTUBE_CHANNEL_SHORT_ITEM_INTELLIGENCE
  | YOUTUBE_CHANNEL_PLAYLIST_ITEM_INTELLIGENCE;

export type YOUTUBE_CHANNEL_INTELLIGENCE_RESPONSE = Omit<
  YOUTUBE_CHANNEL_RESPONSE,
  "items"
> & {
  items: YOUTUBE_CHANNEL_ITEM_INTELLIGENCE[];
  intelligence: YOUTUBE_CHANNEL_INTELLIGENCE_FIELDS;
};
