import type { WithIntelligence } from "../../types";
import type {
  YOUTUBE_VIDEO_SUGGESTED_VIDEOS_RESPONSE,
  YOUTUBE_VIDEO_SUGGESTION_ITEM,
} from "../../../video/types";
import type {
  YOUTUBE_INTELLIGENCE_CHANNEL_TIER_FIELD,
  YOUTUBE_INTELLIGENCE_DURATION_BUCKET_DISTRIBUTION,
  YOUTUBE_INTELLIGENCE_DURATION_FIELDS,
  YOUTUBE_INTELLIGENCE_PUBLISHING_FIELDS,
  YOUTUBE_INTELLIGENCE_TITLE_LENGTH_FIELD,
  YOUTUBE_INTELLIGENCE_TITLE_PATTERN_FIELDS,
} from "../../types";

export type YOUTUBE_VIDEO_SUGGESTION_ITEM_ENRICHED =
  YOUTUBE_VIDEO_SUGGESTION_ITEM & {
    publishedAt: string | null;
    channelSubscribers: number | null;
  };

export type YOUTUBE_VIDEO_SUGGESTION_INTELLIGENCE_FIELDS = {
  suggestionPosition: number;
} & YOUTUBE_INTELLIGENCE_PUBLISHING_FIELDS &
  YOUTUBE_INTELLIGENCE_DURATION_FIELDS &
  YOUTUBE_INTELLIGENCE_TITLE_LENGTH_FIELD &
  YOUTUBE_INTELLIGENCE_TITLE_PATTERN_FIELDS &
  YOUTUBE_INTELLIGENCE_CHANNEL_TIER_FIELD & {
    isSameChannel: boolean | null;
  };

export type YOUTUBE_VIDEO_SUGGESTION_ITEM_INTELLIGENCE = WithIntelligence<
  YOUTUBE_VIDEO_SUGGESTION_ITEM_ENRICHED,
  YOUTUBE_VIDEO_SUGGESTION_INTELLIGENCE_FIELDS
>;

export type YOUTUBE_VIDEO_SUGGESTED_INTELLIGENCE_FIELDS = {
  sameChannelRatio: number;
  avgSuggestionPosition: number;
  durationBucketDistribution: YOUTUBE_INTELLIGENCE_DURATION_BUCKET_DISTRIBUTION;
  channelDiversityCount: number;
  dominantChannelId: string | null;
  dominantChannelCount: number;
};

export type YOUTUBE_VIDEO_SUGGESTED_INTELLIGENCE_RESPONSE = Omit<
  YOUTUBE_VIDEO_SUGGESTED_VIDEOS_RESPONSE,
  "items"
> & {
  items: YOUTUBE_VIDEO_SUGGESTION_ITEM_INTELLIGENCE[];
  intelligence: YOUTUBE_VIDEO_SUGGESTED_INTELLIGENCE_FIELDS;
};
